### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by llafuente** [llafuente/string.c#1]
rough todo list...

---
- [ ] st_len_t count_chars(const string\* haystack, string\* needle)
  
  Each other_str parameter defines a set of characters to count. The intersection of these sets defines the characters to count in str. Any other_str that starts with a caret ^ is negated. The sequence c1-c2 means all characters between c1 and c2. The backslash character \ can be used to escape ^ or - and is otherwise ignored unless it appears at the end of a sequence or the end of a other_str.
- [ ] string\* rem_chars(string\* src, string\* mask)
  
  Returns a copy of str with all characters in the intersection of its arguments deleted. Uses the same rules for building the set of characters as String#count.
- [ ] codepoint iterator
- [ ] separator iterator -> line iterator
- [ ] st_prepend
- [ ] st_reverse

---
- [ ] st_tr
- [ ] st_upto / st_range

---
- [ ] pluralize
- [ ] camel-case
- [ ] snake-case
- [ ] regexp

---

done
- [x] last_index_of
- [x] is_ascii
- [x] center(width, padstr=' ') → new_str
  
  Centers str in width. If width is greater than the length of str, returns a new String of length width with str centered and padded with padstr; otherwise, returns str.
- [x] string\* right(const string\* src, size_t width, string\* padstr=' ')
- [x] string\* left(const string\* src, size_t width, string\* padstr=' ')
- [x] st_is_valid (encoding)
- [x] byte iterator
- [x] span (strspn)
- [x] complementary span (strcspn)
- [x] st_insert(string*\* out, string\* ins, st_len_t pos)
- [x] st_replace(string*\* out, string\* replace, string\* subject, )
